BRAND_NAMES = {
    # "ALLEN-BRADLEY",
    "ABB",
    # "Baumer",
    # "Beckhoff",
    "Balluff",
    # "Delta",
    "Danfoss",
    "Eaton",
    # "Emerson",
    # "Fanuc",
    # "Fluke",
    # "Lenze",
    "Norgren",
    "Omron",
    "Panasonic",
    "Parker",
    "Phoenix",
    # "Pilz",
    # "Pepperl-fuchs",
    "Rockwell",
    "Rexroth",
    "Rittal",
    "Siemens",
    "Sick",
    "SEW",
    "Schneider",
    "Wago",
    "Weidmueller",
    "Yaskawa",
    # "Banner"
}
